In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn import preprocessing 

In [4]:
from sklearn.metrics import accuracy_score

In [5]:
from sklearn.metrics import confusion_matrix

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
dataset = pd.read_csv('train.csv')

In [8]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [9]:
dataset.isnull().sum().sum

<bound method Series.sum of PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64>

In [10]:
dataset["Age"].fillna(dataset.Age.mean(), inplace = True)

In [11]:
label_encoder = preprocessing.LabelEncoder()

In [12]:
dataset['Sex'] = label_encoder.fit_transform(dataset['Sex'])
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [13]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [14]:
dataset1 = dataset.drop('PassengerId', axis = 1)

In [15]:
dataset2 = dataset1.drop('Ticket', axis = 1)

In [16]:
dataset3 = dataset2.drop('Name', axis = 1)

In [17]:
dataset3.head()


Survived  Pclass  Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    1  22.0      1      0   7.2500   NaN        S
1         1       1    0  38.0      1      0  71.2833   C85        C
2         1       3    0  26.0      0      0   7.9250   NaN        S
3         1       1    0  35.0      1      0  53.1000  C123        S
4         0       3    1  35.0      0      0   8.0500   NaN        S

In [18]:
dataset4 = dataset3.drop('Embarked', axis = 1)

In [19]:
dataset5 = dataset4.drop('Cabin', axis = 1)

In [20]:
x = dataset5.drop('Pclass', axis = 1)

In [21]:
x.head()

Survived  Sex   Age  SibSp  Parch     Fare
0         0    1  22.0      1      0   7.2500
1         1    0  38.0      1      0  71.2833
2         1    0  26.0      0      0   7.9250
3         1    0  35.0      1      0  53.1000
4         0    1  35.0      0      0   8.0500

In [22]:
y = dataset3['Pclass']

In [23]:
y.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)

In [25]:
x_train.head()

Survived  Sex        Age  SibSp  Parch     Fare
857         1    1  51.000000      0      0  26.5500
52          1    0  49.000000      1      0  76.7292
386         0    1   1.000000      5      2  46.9000
124         0    1  54.000000      0      1  77.2875
578         0    0  29.699118      1      0  14.4583

In [26]:
x_test.head()

Survived  Sex        Age  SibSp  Parch      Fare
495         0    1  29.699118      0      0   14.4583
648         0    1  29.699118      0      0    7.5500
278         0    1   7.000000      4      1   29.1250
31          1    0  29.699118      1      0  146.5208
255         1    0  29.000000      0      2   15.2458

In [27]:
from sklearn import neighbors

In [28]:
knn = neighbors.KNeighborsClassifier(n_neighbors =3)

In [29]:
knn.fit(x_train,y_train).score(x_test, y_test)

0.8544776119402985

In [30]:
y_pred = knn.predict(x_test)

In [31]:
confusion_matrix(y_test,y_pred)

array([[ 55,   3,   2],
       [ 10,  33,   9],
       [  5,  10, 141]], dtype=int64)

In [32]:
x1 = dataset5.drop('Sex', axis = 1)

In [33]:
y1 = dataset3['Sex']

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x1,y1,test_size = 0.3, random_state = 0)

In [35]:
x_train.head()

Survived  Pclass        Age  SibSp  Parch     Fare
857         1       1  51.000000      0      0  26.5500
52          1       1  49.000000      1      0  76.7292
386         0       3   1.000000      5      2  46.9000
124         0       1  54.000000      0      1  77.2875
578         0       3  29.699118      1      0  14.4583

In [36]:
x_test.head()

Survived  Pclass        Age  SibSp  Parch      Fare
495         0       3  29.699118      0      0   14.4583
648         0       3  29.699118      0      0    7.5500
278         0       3   7.000000      4      1   29.1250
31          1       1  29.699118      1      0  146.5208
255         1       3  29.000000      0      2   15.2458

In [37]:
knn1 = neighbors.KNeighborsClassifier(n_neighbors =3)

In [38]:
knn1.fit(x_train,y_train).score(x_test, y_test)

0.6828358208955224

In [39]:
y_pred1 = knn.predict(x_test)

In [40]:
confusion_matrix(y_test,y_pred)

array([[  0,  31,  22,  46],
       [  0,  39,  24, 106],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]], dtype=int64)

In [41]:
x2 = dataset5.drop('SibSp', axis = 1)

In [42]:
y2 = dataset3['SibSp']

In [43]:
x_train, x_test, y_train, y_test = train_test_split(x2,y2,test_size = 0.3, random_state = 0)

In [44]:
x_train.head()

Survived  Pclass  Sex        Age  Parch     Fare
857         1       1    1  51.000000      0  26.5500
52          1       1    0  49.000000      0  76.7292
386         0       3    1   1.000000      2  46.9000
124         0       1    1  54.000000      1  77.2875
578         0       3    0  29.699118      0  14.4583

In [45]:
x_test.head()

Survived  Pclass  Sex        Age  Parch      Fare
495         0       3    1  29.699118      0   14.4583
648         0       3    1  29.699118      0    7.5500
278         0       3    1   7.000000      1   29.1250
31          1       1    0  29.699118      0  146.5208
255         1       3    0  29.000000      2   15.2458

In [46]:
knn2 = neighbors.KNeighborsClassifier(n_neighbors =3)

In [47]:
knn2.fit(x_train,y_train).score(x_test, y_test)

0.7388059701492538

In [48]:
y_pred1 = knn.predict(x_test)

In [49]:
confusion_matrix(y_test,y_pred)

array([[  0,  38,  33, 110,   0,   0],
       [  0,  27,  10,  28,   0,   0],
       [  0,   2,   2,   3,   0,   0],
       [  0,   1,   0,   5,   0,   0],
       [  0,   2,   1,   4,   0,   0],
       [  0,   0,   0,   2,   0,   0]], dtype=int64)

In [50]:
knn02 = neighbors.KNeighborsClassifier(n_neighbors =2)

In [51]:
knn02.fit(x_train,y_train).score(x_test, y_test)

0.7276119402985075

In [52]:
y_pred1 = knn02.predict(x_test)

In [53]:
confusion_matrix(y_test,y_pred)

array([[  0,  38,  33, 110,   0,   0],
       [  0,  27,  10,  28,   0,   0],
       [  0,   2,   2,   3,   0,   0],
       [  0,   1,   0,   5,   0,   0],
       [  0,   2,   1,   4,   0,   0],
       [  0,   0,   0,   2,   0,   0]], dtype=int64)

In [54]:
knn03 = neighbors.KNeighborsClassifier(n_neighbors =5)

In [55]:
knn03.fit(x_train,y_train).score(x_test, y_test)

0.7313432835820896

In [56]:
y_pred3 = knn02.predict(x_test)

In [57]:
confusion_matrix(y_test,y_pred3)

array([[175,   5,   0,   0,   1,   0],
       [ 49,  14,   2,   0,   0,   0],
       [  2,   3,   0,   2,   0,   0],
       [  2,   2,   0,   2,   0,   0],
       [  3,   1,   0,   0,   3,   0],
       [  1,   0,   0,   0,   0,   1]], dtype=int64)

In [58]:
knn04 = neighbors.KNeighborsClassifier(n_neighbors =80)

In [59]:
knn04.fit(x_train,y_train).score(x_test, y_test)

0.7126865671641791

In [60]:
y_pred4 = knn02.predict(x_test)

In [61]:
confusion_matrix(y_test,y_pred4)

array([[175,   5,   0,   0,   1,   0],
       [ 49,  14,   2,   0,   0,   0],
       [  2,   3,   0,   2,   0,   0],
       [  2,   2,   0,   2,   0,   0],
       [  3,   1,   0,   0,   3,   0],
       [  1,   0,   0,   0,   0,   1]], dtype=int64)

In [62]:
x2 = dataset5.drop('Survived', axis = 1)

In [63]:
y2 = dataset3['Survived']

In [64]:
x_train, x_test, y_train, y_test = train_test_split(x2,y2,test_size = 0.3, random_state = 0)

In [65]:
x_train.head()

Pclass  Sex        Age  SibSp  Parch     Fare
857       1    1  51.000000      0      0  26.5500
52        1    0  49.000000      1      0  76.7292
386       3    1   1.000000      5      2  46.9000
124       1    1  54.000000      0      1  77.2875
578       3    0  29.699118      1      0  14.4583

In [66]:
x_test.head()

Pclass  Sex        Age  SibSp  Parch      Fare
495       3    1  29.699118      0      0   14.4583
648       3    1  29.699118      0      0    7.5500
278       3    1   7.000000      4      1   29.1250
31        1    0  29.699118      1      0  146.5208
255       3    0  29.000000      0      2   15.2458

In [67]:
knn2 = neighbors.KNeighborsClassifier(n_neighbors =3)

In [68]:
knn2.fit(x_train,y_train).score(x_test, y_test)

0.6828358208955224

In [69]:
y_pred1 = knn.predict(x_test)

In [70]:
confusion_matrix(y_test,y_pred)

array([[  0,  27,  24, 117],
       [  0,  43,  22,  35],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]], dtype=int64)

In [71]:
x2 = dataset5.drop('Parch', axis = 1)

In [72]:
y2 = dataset3['Parch']

In [73]:
x_train, x_test, y_train, y_test = train_test_split(x2,y2,test_size = 0.3, random_state = 0)

In [74]:
x_train.head()

Survived  Pclass  Sex        Age  SibSp     Fare
857         1       1    1  51.000000      0  26.5500
52          1       1    0  49.000000      1  76.7292
386         0       3    1   1.000000      5  46.9000
124         0       1    1  54.000000      0  77.2875
578         0       3    0  29.699118      1  14.4583

In [75]:
x_test.head()

Survived  Pclass  Sex        Age  SibSp      Fare
495         0       3    1  29.699118      0   14.4583
648         0       3    1  29.699118      0    7.5500
278         0       3    1   7.000000      4   29.1250
31          1       1    0  29.699118      1  146.5208
255         1       3    0  29.000000      0   15.2458

In [76]:
knn4 = neighbors.KNeighborsClassifier(n_neighbors =3)

In [77]:
knn4.fit(x_train,y_train).score(x_test, y_test)

0.8283582089552238

In [78]:
y_pred1 = knn.predict(x_test)

In [79]:
confusion_matrix(y_test,y_pred)

array([[  0,  45,  34, 125,   0,   0],
       [  0,  16,   9,  15,   0,   0],
       [  0,   7,   3,  11,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   1,   0,   1,   0,   0],
       [  0,   1,   0,   0,   0,   0]], dtype=int64)

# using For loop

In [83]:
def prediction(n):
    X  = dataset5.drop('Pclass', axis = 1)
    Y = dataset5['Pclass']
    for i in range(1,n):
        knn = neighbors.KNeighborsClassifier(n_neighbors = i)
        print(f"Here K value is {i}:")
        x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.3, random_state = 0)
        model = knn.fit(x_train,y_train)
        pred = model.predict(x_test)
        print(f"\nAccuracy when k is {i}",model.score(x_test,y_test))
        
        print(f"Confusion matrix when k is {i} \n",confusion_matrix(y_test,pred))

In [84]:
prediction(10)

Here K value is 1:

Accuracy when k is 1 0.8544776119402985
Confusion matrix when k is 1 
 [[ 56   4   0]
 [  9  34   9]
 [  2  15 139]]
Here K value is 2:

Accuracy when k is 2 0.8134328358208955
Confusion matrix when k is 2 
 [[ 57   3   0]
 [ 11  36   5]
 [  5  26 125]]
Here K value is 3:

Accuracy when k is 3 0.8544776119402985
Confusion matrix when k is 3 
 [[ 55   3   2]
 [ 10  33   9]
 [  5  10 141]]
Here K value is 4:

Accuracy when k is 4 0.8395522388059702
Confusion matrix when k is 4 
 [[ 57   2   1]
 [ 12  32   8]
 [  6  14 136]]
Here K value is 5:

Accuracy when k is 5 0.8507462686567164
Confusion matrix when k is 5 
 [[ 55   3   2]
 [ 10  31  11]
 [  4  10 142]]
Here K value is 6:

Accuracy when k is 6 0.8395522388059702
Confusion matrix when k is 6 
 [[ 55   3   2]
 [ 13  31   8]
 [  6  11 139]]
Here K value is 7:

Accuracy when k is 7 0.832089552238806
Confusion matrix when k is 7 
 [[ 55   3   2]
 [ 12  27  13]
 [  5  10 141]]
Here K value is 8:

Accuracy when k is 8 0