In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn import preprocessing

In [4]:
from sklearn.metrics import accuracy_score

In [5]:
from sklearn.metrics import confusion_matrix

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
dataset = pd.read_csv('train.csv')

In [8]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [9]:
dataset.isnull().sum().sum

<bound method Series.sum of PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64>

In [10]:
dataset["Age"].fillna(dataset.Age.mean(), inplace = True)

In [11]:
dataset.isnull().sum().sum

<bound method Series.sum of PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64>

In [12]:
dataset.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[202 rows x 12 columns]

In [13]:
dataset.isnull().sum().sum

<bound method Series.sum of PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64>

In [14]:
label_encoder = preprocessing.LabelEncoder()

In [80]:
dataset['Sex'] = label_encoder.fit_transform(dataset['Sex'])

dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [16]:
dataset1 = dataset.drop('PassengerId', axis = 1)

In [17]:
dataset2 = dataset1.drop('Ticket', axis = 1)

In [18]:
dataset3 = dataset2.drop('Name', axis = 1)

In [19]:
dataset3.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    1  22.0      1      0   7.2500   NaN        S
1         1       1    0  38.0      1      0  71.2833   C85        C
2         1       3    0  26.0      0      0   7.9250   NaN        S
3         1       1    0  35.0      1      0  53.1000  C123        S
4         0       3    1  35.0      0      0   8.0500   NaN        S

In [20]:
from sklearn import svm

In [21]:
dataset4 = dataset3.drop('Cabin', axis = 1)
dataset5 = dataset4.drop('Embarked', axis = 1)

x= dataset5.drop('Pclass', axis = 1)
x.head()

Survived  Sex   Age  SibSp  Parch     Fare
0         0    1  22.0      1      0   7.2500
1         1    0  38.0      1      0  71.2833
2         1    0  26.0      0      0   7.9250
3         1    0  35.0      1      0  53.1000
4         0    1  35.0      0      0   8.0500

In [22]:
y = dataset5['Pclass']

In [23]:
y.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)

In [25]:
x_train.head()

Survived  Sex        Age  SibSp  Parch     Fare
857         1    1  51.000000      0      0  26.5500
52          1    0  49.000000      1      0  76.7292
386         0    1   1.000000      5      2  46.9000
124         0    1  54.000000      0      1  77.2875
578         0    0  29.699118      1      0  14.4583

In [26]:
x_test.head()

Survived  Sex        Age  SibSp  Parch      Fare
495         0    1  29.699118      0      0   14.4583
648         0    1  29.699118      0      0    7.5500
278         0    1   7.000000      4      1   29.1250
31          1    0  29.699118      1      0  146.5208
255         1    0  29.000000      0      2   15.2458

In [27]:
clf = svm.SVC(gamma = 0.01, C= 100)

In [28]:
clf.fit(x_train, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [29]:
y_pred = clf.predict(x_test)

In [30]:
accuracy_score(y_test, y_pred, normalize = True)

0.8805970149253731

In [31]:
confusion_matrix(y_test, y_pred)

array([[ 56,   3,   1],
       [  6,  42,   4],
       [  4,  14, 138]], dtype=int64)

# using loop to find the  svm for varied dependent and independent variables

In [32]:
dataset4 = dataset3.drop('Cabin', axis = 1)
dataset5 = dataset4.drop('Embarked', axis = 1)
x1= dataset5.drop('Survived', axis = 1)
x1.head()

Pclass  Sex   Age  SibSp  Parch     Fare
0       3    1  22.0      1      0   7.2500
1       1    0  38.0      1      0  71.2833
2       3    0  26.0      0      0   7.9250
3       1    0  35.0      1      0  53.1000
4       3    1  35.0      0      0   8.0500

In [33]:
y1= dataset5['Survived']
y1.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x1,y1,test_size = 0.3, random_state = 0)

In [35]:
x_train.head()

Pclass  Sex        Age  SibSp  Parch     Fare
857       1    1  51.000000      0      0  26.5500
52        1    0  49.000000      1      0  76.7292
386       3    1   1.000000      5      2  46.9000
124       1    1  54.000000      0      1  77.2875
578       3    0  29.699118      1      0  14.4583

In [36]:
x_test.head()

Pclass  Sex        Age  SibSp  Parch      Fare
495       3    1  29.699118      0      0   14.4583
648       3    1  29.699118      0      0    7.5500
278       3    1   7.000000      4      1   29.1250
31        1    0  29.699118      1      0  146.5208
255       3    0  29.000000      0      2   15.2458

In [37]:
clf = svm.SVC(gamma = 0.01, C= 100)

In [38]:
clf.fit(x_train, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [39]:
y_pred = clf.predict(x_test)

In [40]:
accuracy_score(y_test, y_pred, normalize = True)

0.7835820895522388

## For gender as dependent variable

In [41]:
x1= dataset5.drop('Sex', axis = 1)
x1.head()

Survived  Pclass   Age  SibSp  Parch     Fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [42]:
y1= dataset5['Sex']
y1.head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int32

In [43]:
x_train, x_test, y_train, y_test = train_test_split(x1,y1,test_size = 0.3, random_state = 0)

In [44]:
x_train.head()

Survived  Pclass        Age  SibSp  Parch     Fare
857         1       1  51.000000      0      0  26.5500
52          1       1  49.000000      1      0  76.7292
386         0       3   1.000000      5      2  46.9000
124         0       1  54.000000      0      1  77.2875
578         0       3  29.699118      1      0  14.4583

In [45]:
x_test.head()

Survived  Pclass        Age  SibSp  Parch      Fare
495         0       3  29.699118      0      0   14.4583
648         0       3  29.699118      0      0    7.5500
278         0       3   7.000000      4      1   29.1250
31          1       1  29.699118      1      0  146.5208
255         1       3  29.000000      0      2   15.2458

In [46]:
clf = svm.SVC(gamma = 0.01, C= 100)

In [47]:
clf.fit(x_train, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [48]:
y_pred = clf.predict(x_test)

In [49]:
accuracy_score(y_test, y_pred, normalize = True)

0.746268656716418

## For sibsp

In [50]:
x2= dataset5.drop('SibSp', axis = 1)
x2.head()

Survived  Pclass  Sex   Age  Parch     Fare
0         0       3    1  22.0      0   7.2500
1         1       1    0  38.0      0  71.2833
2         1       3    0  26.0      0   7.9250
3         1       1    0  35.0      0  53.1000
4         0       3    1  35.0      0   8.0500

In [51]:
y2= dataset5['SibSp']
y2.head()

0    1
1    1
2    0
3    1
4    0
Name: SibSp, dtype: int64

In [52]:
x_train, x_test, y_train, y_test = train_test_split(x2,y2,test_size = 0.3, random_state = 0)

In [53]:
x_train.head()

Survived  Pclass  Sex        Age  Parch     Fare
857         1       1    1  51.000000      0  26.5500
52          1       1    0  49.000000      0  76.7292
386         0       3    1   1.000000      2  46.9000
124         0       1    1  54.000000      1  77.2875
578         0       3    0  29.699118      0  14.4583

In [54]:
x_test.head()

Survived  Pclass  Sex        Age  Parch      Fare
495         0       3    1  29.699118      0   14.4583
648         0       3    1  29.699118      0    7.5500
278         0       3    1   7.000000      1   29.1250
31          1       1    0  29.699118      0  146.5208
255         1       3    0  29.000000      2   15.2458

In [55]:
clf = svm.SVC(gamma = 0.01, C= 100)

In [56]:
clf.fit(x_train, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [57]:
y_pred = clf.predict(x_test)

In [58]:
accuracy_score(y_test, y_pred, normalize = True)

0.7388059701492538

## For  Parch

In [59]:
x2= dataset5.drop('Parch', axis = 1)
x2.head()

Survived  Pclass  Sex   Age  SibSp     Fare
0         0       3    1  22.0      1   7.2500
1         1       1    0  38.0      1  71.2833
2         1       3    0  26.0      0   7.9250
3         1       1    0  35.0      1  53.1000
4         0       3    1  35.0      0   8.0500

In [60]:
y2= dataset5['Parch']
y2.head()

0    0
1    0
2    0
3    0
4    0
Name: Parch, dtype: int64

In [61]:
x_train, x_test, y_train, y_test = train_test_split(x2,y2,test_size = 0.3, random_state = 0)

In [62]:
x_train.head()

Survived  Pclass  Sex        Age  SibSp     Fare
857         1       1    1  51.000000      0  26.5500
52          1       1    0  49.000000      1  76.7292
386         0       3    1   1.000000      5  46.9000
124         0       1    1  54.000000      0  77.2875
578         0       3    0  29.699118      1  14.4583

In [63]:
x_test.head()

Survived  Pclass  Sex        Age  SibSp      Fare
495         0       3    1  29.699118      0   14.4583
648         0       3    1  29.699118      0    7.5500
278         0       3    1   7.000000      4   29.1250
31          1       1    0  29.699118      1  146.5208
255         1       3    0  29.000000      0   15.2458

In [64]:
clf = svm.SVC(gamma = 0.01, C= 100)

In [65]:
clf.fit(x_train, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [66]:
y_pred = clf.predict(x_test)

In [67]:
accuracy_score(y_test, y_pred, normalize = True)

0.8134328358208955

In [68]:
x5= dataset5
x5.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833
2         1       3    0  26.0      0      0   7.9250
3         1       1    0  35.0      1      0  53.1000
4         0       3    1  35.0      0      0   8.0500

In [77]:
def prediction(n):
    X  = dataset5.drop('Pclass', axis = 1)
    Y = dataset5['Pclass']
    for i in range(1,n):
        
        print(f"Here K value is {i}:")
        x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.3, random_state = 0)
        clf = svm.SVC(gamma = 0.01, C= 100)
        clf.fit(x_train, y_train)
        y_pred = clf.predict(x_test)
        print(f"\nAccuracy when k is {i}",accuracy_score(y_test, y_pred, normalize = True))
        
        print(f"Confusion matrix when k is {i} \n",confusion_matrix(y_test,y_pred))

In [78]:
prediction(10)

Here K value is 1:

Accuracy when k is 1 0.8805970149253731
Confusion matrix when k is 1 
 [[ 56   3   1]
 [  6  42   4]
 [  4  14 138]]
Here K value is 2:

Accuracy when k is 2 0.8805970149253731
Confusion matrix when k is 2 
 [[ 56   3   1]
 [  6  42   4]
 [  4  14 138]]
Here K value is 3:

Accuracy when k is 3 0.8805970149253731
Confusion matrix when k is 3 
 [[ 56   3   1]
 [  6  42   4]
 [  4  14 138]]
Here K value is 4:

Accuracy when k is 4 0.8805970149253731
Confusion matrix when k is 4 
 [[ 56   3   1]
 [  6  42   4]
 [  4  14 138]]
Here K value is 5:

Accuracy when k is 5 0.8805970149253731
Confusion matrix when k is 5 
 [[ 56   3   1]
 [  6  42   4]
 [  4  14 138]]
Here K value is 6:

Accuracy when k is 6 0.8805970149253731
Confusion matrix when k is 6 
 [[ 56   3   1]
 [  6  42   4]
 [  4  14 138]]
Here K value is 7:

Accuracy when k is 7 0.8805970149253731
Confusion matrix when k is 7 
 [[ 56   3   1]
 [  6  42   4]
 [  4  14 138]]
Here K value is 8:

Accuracy when k is 8 