In [1]:
# Day  25 | Assignment  

First take pclass,, gender, SibSP, ParCH, Embarked as dependendent varisable one by one and others are the independent variable and find the confusion matrix.using looping or functions minimize the code

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
from sklearn import preprocessing 

In [5]:
from sklearn.metrics import accuracy_score

In [6]:
from sklearn.metrics import confusion_matrix

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
dataset = pd.read_csv('train.csv')

In [9]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
dataset.isnull().sum().sum

<bound method Series.sum of PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64>

In [11]:
dataset["Age"].fillna(dataset.Age.mean(), inplace = True)

In [12]:
label_encoder = preprocessing.LabelEncoder()

In [13]:
dataset['Sex'] = label_encoder.fit_transform(dataset['Sex'])
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [14]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [15]:
dataset1 = dataset.drop('PassengerId', axis = 1)

In [16]:
dataset2 = dataset1.drop('Ticket', axis = 1)

In [17]:
dataset3 = dataset2.drop('Name', axis = 1)

In [18]:
dataset3.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    1  22.0      1      0   7.2500   NaN        S
1         1       1    0  38.0      1      0  71.2833   C85        C
2         1       3    0  26.0      0      0   7.9250   NaN        S
3         1       1    0  35.0      1      0  53.1000  C123        S
4         0       3    1  35.0      0      0   8.0500   NaN        S

In [19]:
dataset1 = dataset.drop('PassengerId', axis = 1)

In [20]:
dataset2 = dataset1.drop('Ticket', axis = 1)

In [21]:
dataset3 = dataset2.drop('Name', axis = 1)

In [22]:
dataset3.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    1  22.0      1      0   7.2500   NaN        S
1         1       1    0  38.0      1      0  71.2833   C85        C
2         1       3    0  26.0      0      0   7.9250   NaN        S
3         1       1    0  35.0      1      0  53.1000  C123        S
4         0       3    1  35.0      0      0   8.0500   NaN        S

In [23]:
dataset4 = dataset3.drop('Embarked', axis = 1)

In [24]:
dataset5 = dataset4.drop('Cabin', axis = 1)

In [28]:
from sklearn.naive_bayes import *

In [25]:
x = dataset5.drop('Pclass', axis = 1)

In [26]:
x.head()

Survived  Sex   Age  SibSp  Parch     Fare
0         0    1  22.0      1      0   7.2500
1         1    0  38.0      1      0  71.2833
2         1    0  26.0      0      0   7.9250
3         1    0  35.0      1      0  53.1000
4         0    1  35.0      0      0   8.0500

In [27]:
y = dataset3['Pclass']

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 0)

In [31]:
x_train.head()

Survived  Sex        Age  SibSp  Parch     Fare
857         1    1  51.000000      0      0  26.5500
52          1    0  49.000000      1      0  76.7292
386         0    1   1.000000      5      2  46.9000
124         0    1  54.000000      0      1  77.2875
578         0    0  29.699118      1      0  14.4583

In [32]:
from sklearn.naive_bayes import *

In [34]:
clf = BernoulliNB()

In [35]:
y_pred = clf.fit(x_train, y_train).predict(x_test)

In [36]:
accuracy_score(y_test,y_pred, normalize = True)

0.5783582089552238

In [37]:
confusion_matrix(y_test,y_pred)

array([[ 30,   0,  30],
       [ 22,   0,  30],
       [ 30,   1, 125]], dtype=int64)

In [38]:
x1 = dataset5.drop('Sex', axis = 1)

In [39]:
y1 = dataset3['Sex']

In [40]:
x_train, x_test, y_train, y_test = train_test_split(x1,y1, test_size = 0.3, random_state = 0)

In [41]:
x_train.head()

Survived  Pclass        Age  SibSp  Parch     Fare
857         1       1  51.000000      0      0  26.5500
52          1       1  49.000000      1      0  76.7292
386         0       3   1.000000      5      2  46.9000
124         0       1  54.000000      0      1  77.2875
578         0       3  29.699118      1      0  14.4583

In [42]:
clf1 = BernoulliNB()

In [43]:
y_pred = clf1.fit(x_train, y_train).predict(x_test)

In [44]:
accuracy_score(y_test,y_pred, normalize = True)

0.7910447761194029

In [45]:
confusion_matrix(y_test,y_pred)

array([[ 71,  28],
       [ 28, 141]], dtype=int64)

In [46]:
x2 = dataset5.drop('SibSp', axis = 1)

In [47]:
y2 = dataset3['SibSp']

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x2,y2, test_size = 0.3, random_state = 0)

In [49]:
x_train.head()

Survived  Pclass  Sex        Age  Parch     Fare
857         1       1    1  51.000000      0  26.5500
52          1       1    0  49.000000      0  76.7292
386         0       3    1   1.000000      2  46.9000
124         0       1    1  54.000000      1  77.2875
578         0       3    0  29.699118      0  14.4583

In [50]:
clf1 = BernoulliNB()

In [51]:
y_pred = clf1.fit(x_train, y_train).predict(x_test)

In [52]:
accuracy_score(y_test,y_pred, normalize = True)

0.6791044776119403

In [53]:
confusion_matrix(y_test,y_pred)

array([[162,  19,   0,   0,   0,   0],
       [ 45,  20,   0,   0,   0,   0],
       [  4,   3,   0,   0,   0,   0],
       [  4,   2,   0,   0,   0,   0],
       [  4,   3,   0,   0,   0,   0],
       [  1,   1,   0,   0,   0,   0]], dtype=int64)

In [54]:
x2 = dataset5.drop('Parch', axis = 1)

In [55]:
y2 = dataset3['Parch']

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x2,y2, test_size = 0.3, random_state = 0)

In [57]:
x_train.head()

Survived  Pclass  Sex        Age  SibSp     Fare
857         1       1    1  51.000000      0  26.5500
52          1       1    0  49.000000      1  76.7292
386         0       3    1   1.000000      5  46.9000
124         0       1    1  54.000000      0  77.2875
578         0       3    0  29.699118      1  14.4583

In [61]:
clf1 = BernoulliNB()

In [63]:
y_pred = clf1.fit(x_train, y_train).predict(x_test)

In [64]:
accuracy_score(y_test,y_pred, normalize = True)

0.7425373134328358

In [60]:
confusion_matrix(y_test,y_pred)

array([[189,  15,   0,   0,   0],
       [ 30,  10,   0,   0,   0],
       [ 17,   4,   0,   0,   0],
       [  2,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0]], dtype=int64)