# Assignment 14,15

## 1. Create a 3x3x3 array with random value.

In [14]:
from numpy import array
from numpy import vstack
a1 = array([1,2,3])

a2 = array([[4,5,6],[7,8,9]])
a3 = vstack((a1,a2))

In [15]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [1]:
import numpy as np


In [2]:

a = np.zeros((5,5))

In [3]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
a[1][0] = 1

In [5]:
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
a[2][0] =2

In [8]:
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
a[3][0] =3

In [10]:
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
a[4][0] = 4

In [12]:
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0.]])

## 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
import numpy as np

x = np.ones((3,3))

print("checkboard pattern: ")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

checkboard pattern: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 4. Normalize a 5x5 random matrix

In [14]:
import numpy as np
x = np.random.random((5,5))
print("Original Array: ")
print(x)
xmax, xmin = x.max(), x.min()

x = (x - xmin)/(xmax - xmin)
print("After normalization: ")
print(x)

Original Array: 
[[0.0368526  0.21411906 0.18145192 0.99278117 0.20927616]
 [0.87209068 0.26230879 0.46086536 0.69854329 0.90285301]
 [0.48207218 0.93592234 0.64549015 0.90539563 0.4853011 ]
 [0.24516556 0.15742996 0.41558967 0.95497492 0.93465174]
 [0.95864892 0.79119936 0.44316707 0.19089749 0.97272065]]
After normalization: 
[[0.         0.18543902 0.15126582 1.         0.18037284]
 [0.87374528 0.23585046 0.44356113 0.6921968  0.90592585]
 [0.46574565 0.94051979 0.63669772 0.9085857  0.46912344]
 [0.21791686 0.12613637 0.39619808 0.96045075 0.93919061]
 [0.96429414 0.7891246  0.42504689 0.16114686 0.97901463]]


## 5. How to find common values between two arrays?

In [16]:
import numpy as np

array1 = np.array([0, 20, 40, 60])

print("Array1: ",array1)

array2 = [10, 30, 40]
print("Array2: ", array2)
print("common values between two arrays are: ")
print(np.intersect1d(array1,array2))

Array1:  [ 0 20 40 60]
Array2:  [10, 30, 40]
common values between two arrays are: 
[40]


## 6.How to get the dates of yesterday, today and tomorrow?

In [18]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)

today = np.datetime64('today', 'D')

print("Today: ",today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tommorow: ",tomorrow)

Yesterday:  2020-07-25
Today:  2020-07-26
Tommorow:  2020-07-27


__By using  np.datetime64('today', 'D') - np.timedelta64(1, 'D') for yesterday__

__today = np.datetime64('today', 'D')__

__tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')__

## 7. Consider two random array A and B, check if they are equal

In [19]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array: ")
print(x)

y = np.random.randint(0,2,6)
print("Second array: ")
print(y)

print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array: 
[0 0 1 1 1 1]
Second array: 
[0 0 0 1 1 0]
Test above two arrays are equal or not!
False


## 8.Create random vector of size 10 and replace the maximum value by 0

In [20]:
import numpy as np

x= np.random.random(10)

print("Original array: ")
print(x)

x[x.argmax()] = 0

print("Maximum value replaced by 0: ")
print(x)

Original array: 
[0.05508703 0.91155831 0.02516691 0.56239042 0.05777011 0.52169233
 0.82088087 0.66736484 0.45373038 0.92067123]
Maximum value replaced by 0: 
[0.05508703 0.91155831 0.02516691 0.56239042 0.05777011 0.52169233
 0.82088087 0.66736484 0.45373038 0.        ]


## 9. How to print all the values of an array?

In [24]:
import numpy as np
my_array = np.arange(10)

print(my_array)

print("--------------------------------------")
for i in range(0,len(my_array)):
    print(my_array[i])

[0 1 2 3 4 5 6 7 8 9]
--------------------------------------
0
1
2
3
4
5
6
7
8
9


## 10.Subtract the mean of each row of a matrix

In [25]:
import numpy as np
print("Original matrix:\n")

X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims= True)
print(Y)

Original matrix:

[[0.80804917 0.6248386  0.69654015 0.69380213 0.67571072 0.64379835
  0.37469346 0.33236177 0.23500332 0.73366298]
 [0.61306435 0.0262117  0.336976   0.88947193 0.16724734 0.17126328
  0.4324257  0.67256054 0.76806663 0.54077058]
 [0.86287527 0.77907695 0.39452836 0.99255788 0.48465955 0.6455724
  0.84037825 0.09171576 0.61951511 0.40224992]
 [0.132279   0.65948537 0.28229479 0.6463303  0.0731844  0.93851999
  0.83720707 0.94167304 0.15626489 0.51229923]
 [0.51484631 0.30636251 0.39091818 0.69640081 0.11296452 0.53210125
  0.49459661 0.8995509  0.8131515  0.12637346]]

Subtract the mean of each row of the said matrix:

[[ 0.2262031   0.04299253  0.11469409  0.11195606  0.09386465  0.06195229
  -0.2071526  -0.24948429 -0.34684274  0.15181692]
 [ 0.15125854 -0.4355941  -0.12482981  0.42766613 -0.29455847 -0.29054253
  -0.02938011  0.21075474  0.30626083  0.07896477]
 [ 0.25156233  0.167764   -0.21678459  0.38124494 -0.1266534   0.03425945
   0.2290653  -0.51959719  0.00


## 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?



## 12.How to get the diagonal of a dot product?

In [16]:
import numpy as np
from numpy import array
x = np.array([0, 20, 40])
y = np. array([1,2,3])
z= np.diag(x.dot(y))

ValueError: Input must be 1- or 2-d.


## 13.How to find the most frequent value in an array?

In [17]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array: ")
print(x)
print("Most frequent value in the above array: ")
print(np.bincount(x).argmax())

Original array: 
[8 7 1 4 4 4 4 3 5 2 7 8 1 7 4 8 4 8 6 7 1 7 4 2 8 4 0 8 7 3 6 5 4 5 8 0 4
 9 0 9]
Most frequent value in the above array: 
4



## 14.How to get the n largest values of an array

In [19]:
import numpy as np

x =np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


## 15.How to create a record array from a regular array?

In [20]:
import numpy as np

a1 = np.array([1,2,3,4])
a2 = np.array(['Red','Green','white','Orange'])
a3 = np.array([12.20, 15, 20, 40])

result = np.core.records.fromarrays([a1, a2, a3], names ='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'white', 20.)
